# Generated by Django 4.2.6 on 2023-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dockets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rate_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier_name", models.CharField(max_length=255)),
                ("purchase_order", models.CharField(max_length=255)),
            ],
        ),
    ]
