# Generated by Django 4.2.6 on 2023-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_docket_end_time_alter_docket_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='po_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
